[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://supabase.com https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://supabase.com https://*.supabase.co wss://*.supabase.co; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), fullscreen=(self), display-capture=()"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-DNS-Prefetch-Control = "off"

# Redirect all HTTP to HTTPS
[[redirects]]
  from = "http://tony-trivia.netlify.app/*"
  to = "https://tony-trivia.netlify.app/:splat"
  status = 301
  force = true

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Environment variables (example - set actual values in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18" 